### PR TITLE
only copy theme resources when they actually change

### LINKED ISSUE #989: Theme resources are always copied which triggers unnecessary rebuilds
## Description 
Brave theme resources are copied on every build run even if they are the same

## Steps to Reproduce
   1. `npm run build`

## Actual result:
theme resources are copied

## Expected result:
theme resources should only be copied if they are different

## Reproduces how often: 
always

### Reproducible on current release:
yes

### PR DESCRIPTION
**Pull request by bridiver**
fix #989

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

### CODE REVIEW

File: lib/util.js [hunk 1]
```diff
@@ -75,38 +75,74 @@ const util = {
...
+        let destinationFile = output
+        if (fs.statSync(destinationFile).isDirectory()) {
+          destinationFile = path.join(destinationFile, path.basename(sourceFile))
+        }
+
+        // The destination file might be newer when updating chromium so
+        // we check for an exact match on the timestamp. We use seconds instead
+        // of ms because utimesSync doesn't set the times with ms precision
+        if (!fs.existsSync(destinationFile) ||
+            Math.floor(new Date(fs.statSync(sourceFile).mtimeMs).getTime() / 1000) !=
```
Comment (bridiver) [inline lib/util.js]: ideally we'd use a file hash here, but that might take a while

File: lib/util.js [hunk 2]
```diff
@@ -66,47 +66,79 @@ const util = {
...
+    fileMap[path.join(braveResourcesDir, 'settings', 'brave_page_visibility.js')] = path.join(chromeResourcesDir, 'settings', 'brave_page_visibility.js')
+    fileMap[path.join(braveResourcesDir, 'settings', 'brave_appearance_page')] = path.join(chromeResourcesDir, 'settings', 'brave_appearance_page')
 
     if (process.platform === 'darwin') {
       // Copy proper mac app icon for channel to chrome/app/theme/mac/app.icns.
       // Each channel's app icons are stored in brave/app/theme/$channel/app.icns.
       // With this copying, we don't need to modify chrome/BUILD.gn for this.
-      fs.copySync(path.join(braveAppDir, 'theme', 'brave', 'mac', config.channel, 'app.icns'),
-                  path.join(chromeAppDir, 'theme', 'brave', 'mac', 'app.icns'))
+      fileMap[path.join(braveAppDir, 'theme', 'brave', 'mac', config.channel, 'app.icns')] =
```
Comment (simonhong) [inline lib/util.js]: I think these two files (icon and BRANDING) should be handled differently.
When different channel is built from previous, these two files should be copied.

Comment (bridiver) [reply lib/util.js]: I guess it could still be a problem if you switch channels back and forth because you'll end up with the same timestamp for all of them at some point

Comment (bridiver) [reply lib/util.js]: I'll change to hash

**Comment by bbondy** [comment]
0.55.x a4f3eb2199d1b12e57ac52ee381ab202bfd59b3c

**Comment by bbondy** [comment]
0.55.x ac51cfb497c660fb9d5bce0c792c0fce00d78bdb

**Comment by bbondy** [comment]
Needed a small follow up here:
0.55.x 05a6963381e65f8baca626b33c3f6f4fb77ef9be
master b915275a430fe76c3cbebd73c400fd2ac6df9207
