### PR TITLE
Issue 4030: Using SIGKILL instead of SIGTERM to terminate the process on timeout

### LINKED ISSUE #4030: test-security timeout does not work on build machines
## Description 
`npm run test-security` uses timeout to make sure that the browser process is terminated after 2 mins. 

https://github.com/brave/brave-browser/blob/master/lib/start.js#L95

The timeout does not work on `build` machines, and the processes keep running even after 2 mins. Leading to an eventual abort.

### PR DESCRIPTION
**Pull request by jumde**
fix #4030  

**PR Builder passed here**: https://staging.ci.brave.com/job/brave-browser-build-pr/job/PR-4036/4/

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.

## Test Plan:

1. Verify that `npm run test-security` works on build machines.
2. Remove any entry from `lib/whitelistedUrlPrefixes.js` and confirm it fails.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

### CODE REVIEW

**Comment by mihaiplesa** [comment]
We could try SIGTERM first and then SIGKILL (1m after), what do you all think?

**Comment by diracdeltas** [comment]
> We could try SIGTERM first and then SIGKILL (1m after), what do you all think?

that sgtm. or add an env variable for the build machines which need SIGKILL

**Comment by jumde** [comment]
> > We could try SIGTERM first and then SIGKILL (1m after), what do you all think?
> 
> that sgtm. or add an env variable for the build machines which need SIGKILL

I'll add an environment variable. 

@mihaiplesa: let me know if `BRAVE_BUILD=true` sounds good as the env variable and value?

**Comment by mihaiplesa** [comment]
We have a var named `RELEASE_TYPE`, if that is set it's an indication you're in a build machine (it gets values of `release` and `ci`) so we should us it.

File: lib/start.js [hunk 1]
```diff
@@ -94,7 +94,8 @@ const start = (passthroughArgs, buildConfig = config.defaultBuildConfig, options
     stdio: 'inherit',
     timeout: options.network_log ? 120000 : undefined,
     continueOnFail: options.network_log ? true : false,
-    shell: process.platform === 'darwin' ? true : false
+    shell: process.platform === 'darwin' ? true : false,
+    killsignal: options.network_log && process.env.RELEASE_TYPE ? 'SIGKILL' : 'SIGTERM'
```
Comment (diracdeltas) [inline lib/start.js]: this should be `killSignal`: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options

Comment (mihaiplesa) [reply lib/start.js]: my bad, thanks for the catch
